--- 
# packages for centos OpenVPN server
  - name: Update all packages via yum
    become: true
    yum:
      name: '*'
      state: latest

  - name: Enable epel repo 
    become: true
    yum:
      name: epel-release
      state: present

  - name: Install openvpn and easy-rsa
    become: true
    yum:
      name: 
        - openvpn
        - easy-rsa
      state: present
